"""Shared footer for images rendered by the bot."""

from typing import Tuple

from PIL import Image, ImageDraw, ImageFont


IMAGE_CREDIT = "generated by iceWaG"
IMAGE_CREDIT_HEIGHT = 56


def append_image_credit(
    image: Image.Image,
    font: ImageFont.ImageFont,
    *,
    footer_fill: Tuple[int, int, int] = (20, 21, 23),
    text_fill: Tuple[int, int, int] = (238, 235, 225),
    rule_fill: Tuple[int, int, int] = (16, 177, 191),
) -> Image.Image:
    """Append a compact, non-overlapping authorship strip below an image."""
    source = image.convert("RGB")
    result = Image.new(
        "RGB",
        (source.width, source.height + IMAGE_CREDIT_HEIGHT),
        footer_fill,
    )
    result.paste(source, (0, 0))

    draw = ImageDraw.Draw(result)
    draw.rectangle(
        (0, source.height, source.width, source.height + 3),
        fill=rule_fill,
    )
    bbox = draw.textbbox((0, 0), IMAGE_CREDIT, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    x = (source.width - text_width) // 2 - bbox[0]
    y = (
        source.height
        + (IMAGE_CREDIT_HEIGHT - text_height) // 2
        - bbox[1]
        + 1
    )
    draw.text((x, y), IMAGE_CREDIT, fill=text_fill, font=font)
    return result
